### PR TITLE
Fixes online

### PR DESCRIPTION
**Pull request by ja4200wi**

### CODE REVIEW

**Comment by ja4200wi** [comment]
In `customAlert.tsx`, the `visible` prop of the `Modal` component has been modified to default to `false` when `visible` is undefined. This change can prevent runtime errors by ensuring a boolean value is always passed to the `visible` prop.

**Comment by ja4200wi** [comment]
In `App.tsx`, a `GameStateProvider` has been introduced to wrap the `GameScreen` component. This change is beneficial as it suggests the use of context to manage game state, which can lead to cleaner and more manageable code.

**Comment by ja4200wi** [comment]
In `GameScr.tsx`, the integration of hooks like `useGameState` and `useGameLogic` shows a shift towards using custom hooks for handling component logic, which improves code organization and reusability.

**Comment by ja4200wi** [comment]
In `Board.tsx`, there's a new condition added to check if `currentLastMove.from` is 25 or 0. If true, the checker is pushed to `prisonCheckers` instead of `spikes[currentLastMove.from].checkers`. This change seems to handle a special case for the checker's position, possibly for handling the bar in backgammon.

**Comment by ja4200wi** [comment]
In `SmallComponents.tsx`, the message for sharing an invite has been updated to include a TestFlight link, which provides a more direct call-to-action for users to download and test the app.

**Comment by ja4200wi** [comment]
In `gameUtils.tsx`, several utility functions are added or refactored to handle online and local game states. This includes functions for dice transformation, pausing execution, and converting turns between online and local formats. These additions improve the modularity and functionality for managing game state and moves.

**Comment by ja4200wi** [comment]
The `useGameLogic.ts` file has been significantly refactored to separate concerns into multiple hooks like `useGameEffects`, `useGameLogicComputer`, and others. This enhances readability and maintainability by organizing code into logical units.

**Comment by ja4200wi** [comment]
The `useGameEffects.ts` hook has been introduced to manage side effects related to game state, such as syncing online turns and setting player colors. This separation of concerns aligns well with React's philosophy of keeping logic modular and manageable.

**Comment by ja4200wi** [comment]
The new `GameStateContext.js` file establishes a context for managing game state, which enhances state management across components that consume this context. This is a good pattern for managing complex state logic in a React application.

**Comment by ja4200wi** [comment]
The PR introduces a context-based state management solution with the new `GameStateContext` and its provider. However, it would be beneficial to ensure that all the related state and logic are encapsulated within this context to prevent potential prop drilling and to enhance testability and maintainability. Additionally, consider using TypeScript's type definitions for context values to catch potential type-related issues at compile time, which can provide better type safety across the application.

**Comment by ja4200wi** [comment]
### Summary of Changes
This Pull Request introduces several changes and improvements across multiple components of the Backgammon application:

- **App.tsx**: 
  - Wrapped `GameScreen` with `GameStateProvider` to manage game state consistently.
- **Board.tsx**: 
  - Corrected logic for moving checkers to the prison when coming from specific positions.
- **SmallComponents.tsx**: 
  - Updated the sharing message to provide users with a TestFlight link to the app.
- **CustomAlert.tsx**: 
  - Added a default visibility state to the modal component to avoid undefined errors.
- **Game Logic**:
  - **gameUtils.tsx**: Introduced functions for handling online game interactions, such as dice transformations and turn handling.
  - Split large game logic into modular hooks (`useGameEffects`, `useGameLogicOnline`, `useGameTurns`, `useGameSetUp`, `useGameLogicStateManagement`, `useGameLogicComputer`, `useGameHelper`, `GameStateContext`).
  - **GameStateContext.js**: Created a centralized context for managing game state and transitions, improving state management.

### Possible Improvements
- **Code Duplication**: Some functions appear to be duplicated across different files, such as transformation functions in `gameUtils.tsx` and `useGameLogicOnline.ts`. Consider refactoring to reduce redundancy.
- **Comments and Documentation**: Improve inline comments and documentation, especially in complex logic sections, to enhance code readability and maintainability.
- **Error Handling**: Implement comprehensive error handling in async functions to ensure resilience during API calls and data processing.
- **Testing**: Ensure new functionalities and components are covered by tests to prevent future regressions.
- **Magic Numbers**: Replace magic numbers with named constants for better code clarity and maintainability.

These changes and recommendations aim to improve the functionality, maintainability, and scalability of the game application.

**Comment by moritzKallax** [comment]
passt so, super code. wow

**Review by moritzKallax — APPROVED** [review]
super

**Pull request merged**
